### ISSUE TITLE
bogus coverage in LICENSE

### ISSUE THREAD

**Issue by jonassmedegaard** [LibreCat/Catmandu-XSD#1]
Hi,

The file LICENSE begins with "This software is copyright (c) 5 by Patrick Hochstenbach".

I highly doubt Patrick was around 5 years after the death of Jesus, let alone able to create copyrightable digital material back then. :-P

Also, copyright is arguably wrong to include at all in the file LICENSE file at all.

 - Jonas

**Comment by phochste** [comment]
Fixed :-P
